### ISSUE TITLE
Images have different "styles"

### ISSUE THREAD

**Issue by erisam** [genomizer/genomizer-documentation#20]
Images and pictures are drawn differently (perhaps by different authors).

Examples:
Can we give the image "fig:con_serviceDescription" a white background?
Image "fig:MVCimage" is pixelated / zoomed.
All UML diagrams should be drawn in VioletUML as per agreement in the document group.

**Comment by tnaeg** [comment]
Reworked `con_serviceDescription` into tikz like the other pictures.
